export const allCardsArray = [
  {
    keyword: 'nature',
    title: 'Everyone Needs a Special \'Sit Spot\' in Nature',
    description: 'Ever since I read Richard Louv\'s influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...',
    date: 'November 4, 2020',
    source: 'treehugger',
    link: '#',
    image: 'https://imagizer.imageshack.com/img924/1082/cgqweD.png',
    owner: 'kevin',
    isSaved: false,
    _id: Math.random().toString(),
  },
  {
    keyword: 'nature',
    title: 'Nature makes you better',
    description: 'We all know how good nature can make us feel. We have known it for millennia: the sound of the ocean, the scents of a forest, the way dappled sunlight dances through leaves.',
    date: 'February 19, 2019',
    source: 'National Geographic',
    link: '#',
    image: 'https://imagizer.imageshack.com/img922/7828/FxdrAb.png',
    owner: 'kevin',
    isSaved: true,
    _id: Math.random().toString(),
  },
  {
    keyword: 'parks',
    title: 'Grand Teton Renews Historic Crest Trail',
    description: 'The linking together of the Cascade and Death Canyon trails, at their heads, took place on October 1, 1933, and marked the first step in the realization of a plan whereby the hiker will be...',
    date: 'October 19, 2020',
    source: 'National Parks Traveler',
    link: '#',
    image: 'https://imagizer.imageshack.com/img924/1460/5H5jRn.png',
    owner: 'kevin',
    isSaved: true,
    _id: Math.random().toString(),
  },
  {
    keyword: 'Yellowstone',
    title: 'Nostalgic Photos of Tourists in U.S. National Parks',
    description: 'Uri Løvevild Golman and Helle Løvevild Golman are National Geographic Explorers and conservation photographers who just completed a project and book they call their love letter to...',
    date: 'November 4, 2020',
    source: 'National Geographic',
    link: '#',
    image: 'https://imageshack.com/i/pmPlP5xDp',
    owner: 'kevin',
    isSaved: true,
    _id: Math.random().toString(),
  },
  {
    keyword: 'photography',
    title: 'Scientists Don\'t Know Why Polaris Is So Weird ',
    description: 'Humans have long relied on the starry sky to push into new frontiers, sail to the very edge of the world and find their way back home again. Even animals look to the stars to guide them. ',
    date: 'March 16, 2020',
    source: 'Treehugger',
    link: '#',
    image: 'https://imageshack.com/i/pnYUYDYDp',
    owner: 'kevin',
    isSaved: true,
    _id: Math.random().toString(),
  },
  {
    keyword: 'nature',
    title: 'Everyone Needs a Special \'Sit Spot\' in Nature',
    description: 'Ever since I read Richard Louv\'s influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...',
    date: 'November 4, 2020',
    source: 'treehugger',
    link: '#',
    image: 'https://imagizer.imageshack.com/img924/1082/cgqweD.png',
    owner: 'kevin',
    isSaved: false,
    _id: Math.random().toString(),
  },
  {
    keyword: 'nature',
    title: 'Nature makes you better',
    description: 'We all know how good nature can make us feel. We have known it for millennia: the sound of the ocean, the scents of a forest, the way dappled sunlight dances through leaves.',
    date: 'February 19, 2019',
    source: 'National Geographic',
    link: '#',
    image: 'https://imagizer.imageshack.com/img922/7828/FxdrAb.png',
    owner: 'kevin',
    isSaved: true,
    _id: Math.random().toString(),
  },
  {
    keyword: 'parks',
    title: 'Grand Teton Renews Historic Crest Trail',
    description: 'The linking together of the Cascade and Death Canyon trails, at their heads, took place on October 1, 1933, and marked the first step in the realization of a plan whereby the hiker will be...',
    date: 'October 19, 2020',
    source: 'National Parks Traveler',
    link: '#',
    image: 'https://imagizer.imageshack.com/img924/1460/5H5jRn.png',
    owner: 'kevin',
    isSaved: true,
    _id: Math.random().toString(),
  },
  {
    keyword: 'Yellowstone',
    title: 'Nostalgic Photos of Tourists in U.S. National Parks',
    description: 'Uri Løvevild Golman and Helle Løvevild Golman are National Geographic Explorers and conservation photographers who just completed a project and book they call their love letter to...',
    date: 'November 4, 2020',
    source: 'National Geographic',
    link: '#',
    image: 'https://imageshack.com/i/pmPlP5xDp',
    owner: 'kevin',
    isSaved: true,
    _id: Math.random().toString(),
  },
  {
    keyword: 'photography',
    title: 'Scientists Don\'t Know Why Polaris Is So Weird ',
    description: 'Humans have long relied on the starry sky to push into new frontiers, sail to the very edge of the world and find their way back home again. Even animals look to the stars to guide them. ',
    date: 'March 16, 2020',
    source: 'Treehugger',
    link: '#',
    image: 'https://imageshack.com/i/pnYUYDYDp',
    owner: 'kevin',
    isSaved: true,
    _id: Math.random().toString(),
  },
];

export const savedCardsArray = allCardsArray.slice(1);
